[package]
name = "styl"
version = "0.0.1"
edition = "2021"

[lib]
name = "styl"
path = "src/lib.rs"

[[bin]]
name = "styl"
path = "src/main.rs"

[dependencies]
chrono     = { version = "0.4", features = ["serde"] }
clap       = { version = "4", features = ["derive"] }
csscolorparser = "0.8"
geojson    = "1"
html-escape = "0.2"
indexmap   = { version = "2", features = ["serde"] }
serde      = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
thiserror  = "1"
toml       = "0.8"

[dev-dependencies]
insta      = "1"
tempfile   = "3"
