name: MSRV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust 1.82
        uses: dtolnay/rust-toolchain@1.89
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
